#! /bin/sh

# startup programs
sxhkd &
dunst &
feh --bg-center $HOME/.config/bspwm/wallpaper/errors.jpg --image-bg "#090909" &
$HOME/.config/polybar/launch.sh

#
# base
#
bspc config focus_follows_pointer false
bspc config click_to_focus button1
bspc config pointer_modifier mod1
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

# display
bspc monitor 'eDP-1' -d term web dev img file conf
# bspc monitor 'eDP-1' -d img file conf
bspc monitor 'HDMI-2' -d term web dev img file conf

#
# visual configuration
#
bspc config border_width         0
bspc config window_gap           2

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# colorscheme
bspc config normal_border_color "#1d2021"
bspc config active_border_color "#a89984"
bspc config focused_border_color "#ebdbb2"
bspc config presel_feedback_color "#1d2021"

#
# rules
#
bspc rule -a Sxiv state=floating
bspc rule -a feh state=floating
bspc rule -a Zathura state=tiled

# desktop 1
bspc rule -a kitty desktop='^1' state=tiled follow=on

# desktop 2
bspc rule -a firefox desktop='^2' follow=on
bspc rule -a keepassx desktop='^2' follow=on

# desktop 3
bspc rule -a code-oss desktop='^3' follow=on

# desktop 4
bspc rule -a telegram-desktop desktop='^4' follow=on
bspc rule -a Discord desktop='^4' follow=on

# desktop 5
bspc rule -a Thunar desktop='^5' state=floating

# desktop 6
bspc rule -a Arandr desktop='^6' state=floating
bspc rule -a Pavucontrol desktop='^6' state=floating
bspc rule -a Lxappearance desktop='^6' state=floating

# external
bspc rule -a Stremio desktop='^7' state=fullscreen
